app/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView
)

api_v0_urlpatterns = [
    path(
        'schema/',
        SpectacularAPIView.as_view(),
        name='api-schema'
    ),
    path(
        'docs/',
        SpectacularSwaggerView.as_view(url_name='api-schema'),
        name='api-docs'
    ),
    path(
        'redoc/',
        SpectacularRedocView.as_view(url_name='api-schema'),
        name='api-redoc'
    ),
    # path('api/user/', include('user_auth_token.urls')),
    path('auth/', include('authentication.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v0/', include(api_v0_urlpatterns)),
    path('', include('web.urls')),
]

authentication/urls.py
from django.urls import path, include
from .views import (
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    CustomTokenVerifyView,
    LogoutView,
)

app_name = 'authentication'

urlpatterns = [
    path('', include('djoser.urls')),
    # path('', include('djoser.urls.jwt')),
    # # override the default jwt token views
    path(
        'jwt/create/',
        CustomTokenObtainPairView.as_view(),
        name='jwt-create'
    ),
    path(
        'jwt/refresh/',
        CustomTokenRefreshView.as_view(),
        name='jwt-refresh'
    ),
    path(
        'jwt/verify/',
        CustomTokenVerifyView.as_view(),
        name='jwt-verify'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
]

user/urls.py
"""
URL mappings for the user API.
"""
from django.urls import path
from user import views


app_name = 'user'

urlpatterns = [
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('token/', views.CreateTokenView.as_view(), name='token'),
    path('me/', views.ManageUserView.as_view(), name='me'),
]

web/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'web'

urlpatterns = [
    path('', TemplateView.as_view(template_name="web/home.html"), name="home"),
    path('privacy/', TemplateView.as_view(template_name="web/privacy.html"), name='privacy'),
    path('imprint/', TemplateView.as_view(template_name="web/imprint.html"), name='imprint'),
    path('activation/<str:uid>/<str:token>/', views.ActivationView.as_view(), name='activation'),
    # path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

core/models.py
"""
Database models.
"""
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    """Manager for users."""

    def create_user(self, email, password=None, **extra_fields):
        """Create, save and return a new user."""
        if not email:
            raise ValueError('User must have an email address.')

        if 'first_name' not in extra_fields \
                or not extra_fields.get("first_name"):
            raise ValueError('User must have a first name.')

        if 'last_name' not in extra_fields \
                or not extra_fields.get("last_name"):
            raise ValueError('User must have a last name.')

        user = self.model(
            email=self.normalize_email(email).lower(),
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password, **extra_fields):
        """Create and return a new superuser."""
        user = self.create_user(
            email,
            password,
            **extra_fields,
        )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system."""
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

web/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.conf import settings
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework_simplejwt.views import (
    TokenObtainPairView,  # Token Create endpoint
    TokenRefreshView,  # Token refresh endpoint
    TokenVerifyView,  # Token verify endpoint
)


class CustomTokenObtainPairView(TokenObtainPairView):

    # override post
    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)

        if response.status_code == 200:
            access_token = response.data.get('access')
            refresh_token = response.data.get('refresh')

            response.set_cookie(
                'access',
                access_token,
                max_age=settings.AUTH_COOKIE_ACCESS_MAX_AGE,
                path=settings.AUTH_COOKIE_PATH,
                secure=settings.AUTH_COOKIE_SECURE,
                httponly=settings.AUTH_COOKIE_HTTP_ONLY,
                samesite=settings.AUTH_COOKIE_SAMESITE
            )
            response.set_cookie(
                'refresh',
                refresh_token,
                max_age=settings.AUTH_COOKIE_REFRESH_MAX_AGE,
                path=settings.AUTH_COOKIE_PATH,
                secure=settings.AUTH_COOKIE_SECURE,
                httponly=settings.AUTH_COOKIE_HTTP_ONLY,
                samesite=settings.AUTH_COOKIE_SAMESITE
            )

        return response


class CustomTokenRefreshView(TokenRefreshView):
    def post(self, request, *args, **kwargs):
        refresh_token = request.COOKIES.get('refresh')

        if refresh_token:
            request.data['refresh'] = refresh_token

        response = super().post(request, *args, **kwargs)

        if response.status_code == 200:
            access_token = response.data.get('access')
            response.set_cookie(
                'access',
                access_token,
                max_age=settings.AUTH_COOKIE_ACCESS_MAX_AGE,
                path=settings.AUTH_COOKIE_PATH,
                secure=settings.AUTH_COOKIE_SECURE,
                httponly=settings.AUTH_COOKIE_HTTP_ONLY,
                samesite=settings.AUTH_COOKIE_SAMESITE
            )

        return response


class CustomTokenVerifyView(TokenVerifyView):
    def post(self, request, *args, **kwargs):
        access_token = request.COOKIES.get('access')

        if access_token:
            request.data['token'] = access_token

        return super().post(request, *args, **kwargs)


class LogoutView(APIView):
    def post(self, request, *args, **kwargs):
        response = Response(status=status.HTTP_204_NO_CONTENT)
        response.delete_cookie('access')
        response.delete_cookie('refresh')

        return response

user/views.py
"""
Views for the user API.
"""
from rest_framework import generics, authentication, permissions
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings

from user.serializers import (
    UserSerializer,
    AuthTokenSerializer,
)


class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system."""
    serializer_class = UserSerializer


class CreateTokenView(ObtainAuthToken):
    """Create a new auth token for user."""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


class ManageUserView(generics.RetrieveUpdateAPIView):
    """Manage the authenticated user."""
    serializer_class = UserSerializer
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get_object(self):
        """Retrieve and return the authenticated user."""
        return self.request.user

web/views.py
from django.views.generic import TemplateView

# Create your views here.
class ActivationView(TemplateView):
    template_name="web/activation.html"

web/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>BoatSpot</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {# Load the tag library #}
    {% load django_bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% bootstrap_javascript %}
  </head>
  <body>
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              {% if user.is_authenticated %}
              <li>Hello {{ user.first_name }} {{ user.last_name }}</li>
              {% if user.is_staff %}
              <li><hr /></li>
              <li><a href="{% url 'api-docs' %}">OpenAPI</a></li>
              {% endif %}
              {% endif %}
              <li><a href="{% url 'web:home' %}">Home</a></li>
              <li><a href="{% url 'web:privacy' %}">Privacy</a></li>
              <li><a href="{% url 'web:imprint' %}">Imprint</a></li>
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

web/templates/web/home.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Home</h1>
  <p>
    Welcome to BoatSpot
  </p>
  <p>Download our App</p>
  <ul>
    <li><strong>Android</strong></li>
    <li><strong>IOS</strong></li>
  </ul>
{% endblock %}

web/templates/web/imprint.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Imprint</h1>
  <p>
    BoatSpot GmbH & Co. KG AG<br />
    Somewhere Over the rainbow
  </p>
{% endblock %}

web/templates/web/privacy.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Privacy</h1>
  <p>
    We share none of your data ... with you ;-)
  </p>
{% endblock %}